baseURL = "https://blog.mairamartins.com"
languageCode = "en-us"
theme = "hyde"
title = "Ma√≠ra K"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-09"
