# Site Settings
baseURL = "https://mairamartins.com/blog/"
languageCode = "en"
title = "Maira Martins K"
theme = "cactusplus"
googleAnalytics = ""
hasCJKLanguage = false

[params]
	author = "Maira Martins K"
	description = "A blog about front-end web development."
	bio = "Programmer. Photographer. Lover of dogs, cats, pizza, comics, computers and everything in between. Currently digging React.js!"
	twitter = "mairamartinsk"

	enableRSS = false
	enableToc = false
	enableDisqus = false
	enableSummary = false
	useDescriptionReplaceSummary = false
	enableBaiduAnalytics = false
	enableGoogleAnalytics = true
	enableTwitterCard = true
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = ["css/custom.css"]
	customJS = ["js/app.js"]

	# Optional: Customize or translate strings below
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# Show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = false
	tweet = "Share on Twitter"
	share = "Share on Facebook"

	# 404 Page
	title404 = ""
	subtitle404 = ""

	# Social icons served by "mono-social" or "font-awesome"
	iconFont = "mono-social"
	socialIconStyle = "circle"

# Add additional social links
[social]
	github = "https://www.github.com/mairamartinsk"
	twitter = "https://www.twitter.com/mairamartinsk"
	linkedin = "https://www.linkedin.com/in/mairamartinsk"
	instagram = "https://www.instagram.com/mairamartinsk"
